version: '3'

services: 
    db:
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: sdb
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
    dbeaver:
      image: dbeaver/cloudbeaver:latest
      ports:
        - "8080:8978"
      volumes:
        - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace
